\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{slides}

\RequirePackage[english]{babel}

\LoadClass{article}

\RequirePackage{mathspec}
\RequirePackage{xltxtra}

\RequirePackage[top=0mm, bottom=0mm, left=0mm, right=0mm, paperwidth=120mm, paperheight=90mm]{geometry}
\RequirePackage{ifthen}
\RequirePackage{refcount}
\RequirePackage{lastpage}
\RequirePackage{multicol}
\setlength{\multicolsep}{0pt}
\RequirePackage{url}
\RequirePackage{xspace}
\RequirePackage{tikz}
\usetikzlibrary{calc}
\RequirePackage[tracking=normal]{savetrees}

\def\tez{{\fontspec[Scale=MatchLowercase]{CODE2000.TTF}\selectfont{ꜩ}}\xspace}

\let\olditem\item
\renewcommand{\item}{%
  \setlength{\itemsep}{0pt}%
  \setlength{\parsep}{0pt}%
  \setlength{\parskip}{0pt}\olditem}

\definecolor{darkcolor}{RGB}{0, 0, 0}
%\definecolor{lightcolor}{RGB}{230, 190, 0}
\definecolor{lightcolor}{RGB}{180, 180, 180}

\def\slidebackground#1#2#3{
  \node [rotate=7] at (90mm, 20mm) {\fontsize{80mm}{80mm}\selectfont\color{#1!#2!#3}\tezoslogo[#1]};
  \node [rotate=7] at (10mm, 70mm) {\fontsize{50mm}{50mm}\selectfont\color{#1!#2!#3}\tezoslogo[#1]};
}

% fonts
\setallmainfonts[Scale=MatchLowercase, AutoFakeBold, AutoFakeSlant]{exljbris - Museo-300.otf}
\setallmonofonts[Scale=MatchLowercase, AutoFakeBold, AutoFakeSlant]{Inconsolata}

%listings
\RequirePackage{listings}

\def\thelstnumber{\color{lightcolor!50!darkcolor}\arabic{lstnumber}\hbox to 0.5ex{\hbox to 1ex{}:}}

\lstnewenvironment{code}{%
  \lstset{basicstyle=\small\ttfamily,%
    escapechar=\$,
    numbers=left,%
    xleftmargin=6ex}%
}{}

\lstnewenvironment{smallcode}{%
  \lstset{basicstyle=\scriptsize\ttfamily,%
    numbers=left,%
    xleftmargin=6ex}%
}{}

\lstnewenvironment{makefile}{%
  \lstset{basicstyle=\small\ttfamily,%
    numbers=left,%
    language=make,%
    xleftmargin=6ex}%
}{}

\lstnewenvironment{ocaml}{%
  \lstset{basicstyle=\small\ttfamily,%
    numbers=left,%
    escapechar=\$,
    xleftmargin=6ex,%
    language=Caml,%
    morekeywords={node, replace, class, object, children, prop, external,%
      val, struct, sig, functor, module, with, include, methodtual, private, inherit, method},
    deletekeywords={value},
    stringstyle=\color{darkcolor!50!darkgray}\itshape, %
    commentstyle=\color{darkcolor!50!gray}\small\ttfamily,%
    keywordstyle=\color{darkcolor!50!black}\bfseries}%
\vskip-1ex}{\vskip-1ex}

\lstnewenvironment{dlambda}{%
  \lstset{basicstyle=\scriptsize\ttfamily,%
    numbers=left,%
    escapechar=\$,
    xleftmargin=6ex,%
    language=Caml,%
    morekeywords={node, replace, class, object, children, prop, external,%
      val, struct, sig, functor, module, with, include},
    deletekeywords={value, match},
    stringstyle=\color{darkcolor!50!darkgray}\itshape, %
    commentstyle=\scriptsize\ttfamily,%
    keywordstyle=\color{darkcolor!50!black}\bfseries}%
}{}


\lstnewenvironment{htmljscode}{%
  \lstset{basicstyle=\footnotesize\ttfamily,%
    numbers=left,%
    escapechar=\&,
    xleftmargin=6ex,%
    morekeywords={var, function, of, let},%
    otherkeywords={.,=,;,(,),\{,\},[,]},%
    keywordstyle=\color{darkcolor!50!black}\bfseries,%
    morestring=[b]",%
    commentstyle=\color{darkcolor!50!gray}\small\ttfamily,%
    moredelim=*[s][\color{darkcolor!50!black}\bfseries]{<}{>},%
    moredelim=*[s][\color{darkcolor!50!darkgray}\itshape]{/*}{*/},%
    stringstyle=\color{darkcolor!50!darkgray}\itshape}%
}{}

\lstnewenvironment{phpcode}{%
  \lstset{basicstyle=\small\ttfamily,%
    numbers=left,%
    escapechar=\&,
    xleftmargin=6ex,%
    morekeywords={function, static, class, array, echo, global},%
    otherkeywords={.,=,;,(,),\{,\},[,]},%
    keywordstyle=\color{darkcolor!50!black}\bfseries,%
    morestring=[b]",%
    commentstyle=\color{darkcolor!50!gray}\small\ttfamily,%
    moredelim=*[s][\color{darkcolor!50!darkgray}\itshape]{/*}{*/},%
    stringstyle=\color{darkcolor!50!darkgray}\itshape}%
}{}


\lstnewenvironment{jscode}{%
  \lstset{basicstyle=\small\ttfamily,%
    numbers=left,%
    xleftmargin=6ex,%
    language=Java,%
    morekeywords={var, function, of, let},%
    otherkeywords={.,<,>,!,=,;,(,),\{,\},[,]},%
    commentstyle=\color{darkcolor!50!gray}\small\ttfamily,%
    stringstyle=\color{darkcolor!50!darkgray}\itshape, %
    keywordstyle=\color{darkcolor!50!black}\bfseries}%
}{}

\lstnewenvironment{perlcode}{%
  \lstset{numbers=left,%
    xleftmargin=6ex,%
    language=Perl,%
    stringstyle=\color{darkcolor!50!darkgray}\itshape, %
    keywordstyle=\color{darkcolor!50!black}\bfseries}%
}{}

\lstnewenvironment{javacode}{%
  \lstset{numbers=left,%
    xleftmargin=6ex,%
    language=Java,%
    otherkeywords={.,<,>,!,=,;,(,),\{,\},[,]},%
    stringstyle=\color{darkcolor!50!darkgray}\itshape, %
    keywordstyle=\color{darkcolor!50!black}\bfseries}%
}{}

\lstnewenvironment{ccode}{%
  \lstset{basicstyle=\small\ttfamily,%
    numbers=left,%
    xleftmargin=6ex,%
    language=C,%
    otherkeywords={.,<,>,!,=,;,(,),\{,\},[,]},%
    stringstyle=\color{darkcolor!50!darkgray}\itshape, %
    keywordstyle=\color{darkcolor!50!black}\bfseries}%
}{}

% main
\def\newfield#1{
  \global\expandafter\newbox\csname #1box\endcsname
  \global\expandafter\newif\csname if#1present\endcsname
  \global\csname #1presentfalse\endcsname
  \global\expandafter\def\csname #1\endcsname##1{
    \global\expandafter\setbox\csname #1box\endcsname\hbox{##1}
    \global\csname #1presenttrue\endcsname
  }
  \global\expandafter\def\csname put#1\endcsname{
    \expandafter\unhcopy\csname #1box\endcsname
  }
  \global\expandafter\def\csname reset#1\endcsname{
    \global\csname #1presentfalse\endcsname
  }
}

\def\newfield#1{
  \global\expandafter\newif\csname if#1present\endcsname
  \global\csname #1presentfalse\endcsname
  \global\expandafter\def\csname #1\endcsname##1{
    \global\expandafter\def\csname #1box\endcsname{##1}
    \global\csname #1presenttrue\endcsname
  }
  \global\expandafter\def\csname put#1\endcsname{
    \csname #1box\endcsname
  }
  \global\expandafter\def\csname reset#1\endcsname{
    \global\csname #1presentfalse\endcsname
  }
}

\newfield{mainauthor}
\newfield{maintitle}
\newfield{mainsubtitle}
\newfield{confname}
\newfield{confdate}
\newfield{confshortname}
\newfield{title}
\newfield{subtitle}
\confdate{\today}

\newcount\toctoci\toctoci=0\relax
\expandafter\edef\csname toctoc0\endcsname{}
\edef\completetoc{}

\def\toctocbigslide#1#2{%
  \global\expandafter\edef\csname toctoc#1\endcsname{}%
  \global\edef\completetoc{%
    \completetoc%
    \noindent#2\par}%
}
\def\toctocslide#1#2{%
  \global\expandafter\edef\csname toctoc#1\endcsname{%
    \csname toctoc#1\endcsname%
    \noindent#2\par}%
}

\InputIfFileExists{\jobname.toctoc}\relax

\newwrite\toctocf
\immediate\openout\toctocf=\jobname.toctoc

\def\recordtoctocbigslide#1{%
  \global\advance\toctoci by 1\relax%
  \immediate\write\toctocf{\string\toctocbigslide{\the\toctoci}{#1}}%
}
\def\recordtoctocslide#1{%
  \immediate\write\toctocf{\string\toctocslide{\the\toctoci}{#1}}%
}
\def\replaytoctoc{%
  \advance\toctoci by 1\relax%
  \csname toctoc\the\toctoci\endcsname%
}
\def\replaycompletetoctoc{%
  \completetoc%
}


\newbox\slide@box
\newdimen\top@content
\newcount\slide@idx
\newcount\slide@num
\global\slide@num= 0\relax%
\newenvironment{slide}[1][auto]{%
  \newif\ifhidden\hiddenfalse%
  \def\notintoc{\global\hiddentrue}%
  \global\advance\slide@num by 1\relax%
  \resettitle{}%
  \global\slide@idx= 1\relax%
  \def\startpage{%
    \resetsubtitle{}%
    \top@content=90mm%
    \ifthenelse{\equal{#1}{full}}{%
      \setbox\slide@box\hbox\bgroup\begin{minipage}[t][68mm]{114mm}%
    }{
      \setbox\slide@box\hbox\bgroup\begin{minipage}{114mm}%
    }%
  }%
  \def\shippage{%
    \end{minipage}\egroup%
    \noindent\begin{tikzpicture}
      % background & clipping
      \clip (0,0) rectangle (120mm, 90mm) ;
      \slidebackground{white}{95}{darkcolor}
      % header
      \iftitlepresent
        %\fill [lightcolor!50!darkcolor] (0mm, 88mm) rectangle (120mm, 90mm) ;
        %\shade [top color=lightcolor!50!darkcolor, bottom color=white] (0mm, 88mm) rectangle (120mm, 80mm) ;
      \node (TN) at (0mm, 84mm) [text width=120mm, anchor=base west, text height=5mm, text depth=2mm, inner sep=0] {%
        ~\color{darkcolor}\Large\puttitle%
      } ;
      \ifthenelse{\equal{\pageref{slide:start:\the\slide@num}}{\pageref{slide:end:\the\slide@num}}}{}{%
        \fill [lightcolor] (120mm, 90mm) -- +(-13mm, 0) -- +(-13mm, -15mm) -- +(0, -15mm) ;
      }
      \begin{scope}
        \clip (0mm, 80mm) -- (120mm, 84mm) -- (120mm, 90mm) -- (0mm, 90mm) ;
        \fill [darkcolor] (0mm, 0mm) rectangle (120mm, 90mm) ;
        \node at (0mm, 84mm) [text width=120mm, anchor=base west, text height=5mm, text depth=2mm, inner sep=0] {%
          ~\color{lightcolor}\Large\puttitle%
        } ;
      \end{scope}
      \ifthenelse{\equal{\pageref{slide:start:\the\slide@num}}{\pageref{slide:end:\the\slide@num}}}{}{%
        \node at (118mm, 78mm) [anchor=base east, text height=5mm, text depth=2mm, inner sep=0] {%
          \color{darkcolor}\Large%
            \newcount\@tmpc%
            \@tmpc= 1\relax%
            \advance\@tmpc by \getpagerefnumber{slide:end:\the\slide@num}\relax%
            \advance\@tmpc by -\getpagerefnumber{slide:start:\the\slide@num}\relax%
            \the\slide@idx~/~\the\@tmpc%
          } ;
        }%
        \global\advance\top@content by -7mm%
        \ifsubtitlepresent
          \node (TN) at (0mm, 79mm) [anchor=base west] {%
            ~~\color{darkcolor}\large\putsubtitle%
          } ;
          \global\advance\top@content by -7mm%
        \fi
      \fi
      % footer
      \ifmaintitlepresent
      \begin{scope}
        \clip (0, 0) -- (0, 6mm) -- (120mm, 10mm) -- (120mm,0) ;
        \node (CN) at (60mm, 2mm) [anchor=base, text height=40mm, text depth=4mm, fill=lightcolor, inner sep=0] {%
          \Large\color{darkcolor}\strut~~~\putmaintitle~~~~\strut%
        } ;
        \ifconfnamepresent
          \node at (2mm, 2mm) [inner sep=0, anchor=base west, text height=4mm, text depth=4mm] {%
            \color{darkcolor}\ifconfshortnamepresent\putconfshortname\else\putconfname\fi%
          } ;
        \fi
      \end{scope}
      \fi
      \node at (118mm, 2mm) [anchor=base east, inner sep=0, text height=4mm, text depth=4mm]
        {\color{darkcolor}\large\thepage~/~\pageref{LastPage}} ;
      % body
      \newdimen\@tmpd%
      \@tmpd=\top@content%
      \advance\@tmpd by -7mm%
      \@tmpd=0.5\@tmpd%
      \advance\@tmpd by 7mm%
      \node at (2mm, \@tmpd) [anchor=west, inner sep=1mm] {\box\slide@box} ;
    \end{tikzpicture}%
  }%
  \def\split{%
    \shippage%
    \clearpage%
    \global\advance\slide@idx by 1\relax%
    \startpage%
  }%
  \label{slide:start:\the\slide@num}
  \startpage%
}{%
  \shippage%
  \label{slide:end:\the\slide@num}
  \ifhidden\else\iftitlepresent\recordtoctocslide{\puttitle}\fi\fi%
  \clearpage%
}

\newenvironment{bigslide}[1][]{%
  \title{~~}%
  \resetsubtitle{}%
  \def\startpage{%
    \top@content=90mm%
    \setbox\slide@box\hbox\bgroup%
    \begin{minipage}{104mm}%
      \centering\color{black}\large\strut%
  }%
  \def\toc{\color{darkcolor}\replaytoctoc}%
  \def\shippage{%
      \par%
    \end{minipage}\egroup%
    \noindent\begin{tikzpicture}
      % background & clipping
      \clip (0,0) rectangle (120mm, 90mm) ;
      % text
      \node (TT) at (60mm, 46mm) [anchor=south, text width=\paperwidth, text centered] {%
        \color{lightcolor}\huge\strut\puttitle%
          \ifsubtitlepresent\\ \Large \putsubtitle\fi%
        } ;
        \slidebackground{white}{95}{darkcolor}
        \begin{scope}
          \clip ($(TT.north west)+(0, 0mm)$) -- ($(TT.north east)+(0, 4mm)$) -- (120mm, 90mm) -- (0, 90mm) -- cycle ;
          \fill [lightcolor] (0,0) rectangle (120mm, 90mm) ;
          \slidebackground{lightcolor}{95}{white}
        \end{scope}
      \fill [darkcolor]
        ($(TT.south west)+(0, -4mm)$) -- ($(TT.north west)+(0, 0mm)$) --
        ($(TT.north east)+(0, 4mm)$) -- ($(TT.south east)+(0, 0mm)$) -- cycle ;
      \node at (60mm, 46mm) [anchor=south, text width=\paperwidth, text centered] {%
        \color{lightcolor}\huge\strut\puttitle%
          \ifsubtitlepresent\\ \Large \putsubtitle\fi%
        } ;
      \node at (TT.south) [anchor=north, yshift=-3mm] {%
        \box\slide@box
      } ;
      % footer
      \ifmaintitlepresent
      \begin{scope}
        \clip (0, 0) -- (0, 6mm) -- (120mm, 10mm) -- (120mm,0) ;
        \node (CN) at (60mm, 2mm) [anchor=base, text height=40mm, text depth=4mm, fill=lightcolor, inner sep=0] {%
          \Large\color{darkcolor}\strut~~~\putmaintitle~~~~\strut%
        } ;
        \ifconfnamepresent
          \node at (2mm, 2mm) [inner sep=0, anchor=base west, text height=4mm, text depth=4mm] {%
            \color{darkcolor}\ifconfshortnamepresent\putconfshortname\else\putconfname\fi%
          } ;
        \fi
      \end{scope}
      \fi
      \node at (118mm, 2mm) [anchor=base east, inner sep=0, text height=4mm, text depth=4mm]
        {\color{darkcolor}\large\thepage~/~\pageref{LastPage}} ;
    \end{tikzpicture}%
    \clearpage%
  }%
  \startpage%
}{%
  \shippage%
  \recordtoctocbigslide{\puttitle}
}

\def\hilightbullet{{\color{darkcolor}$\bullet$}}
\AtBeginDocument{
\renewcommand{\labelitemi}{~~~~~{\large \color{darkcolor}$\bullet$}}
\renewcommand{\labelitemii}{~~~~~\hilightbullet}
\renewcommand{\labelitemiii}{~~~~~\color{darkcolor}$-$}
}

\def\maketitle{%
  \noindent\begin{tikzpicture}
    % background & clipping
    \clip (0,0) rectangle (120mm, 90mm) ;
    \slidebackground{white}{95}{darkcolor}
    \begin{scope}
      \clip (0,44mm) -- (0, 90mm) -- (120mm, 90mm) -- (120mm, 48mm);
      \fill [darkcolor] (0,0) rectangle (120mm, 90mm) ;
      \slidebackground{darkcolor}{80}{white}
    \end{scope}
    % text
    \node (TT) at (60mm, 46mm) [anchor=south, text width=\paperwidth, text centered] {%
      \color{lightcolor}\huge\strut\putmaintitle%
          \ifmainsubtitlepresent\\ \Large \putmainsubtitle\fi%
    } ;
    \node at (TT.south) [anchor=north, yshift=-1mm] {%
      \begin{minipage}{104mm}%
        \centering\large\strut%
        \putmainauthor\\[1mm]
        \hilight{\putconfdate} \par
      \end{minipage}%
    } ;
    % footer
    \ifconfnamepresent
      \ifmaintitlepresent
      \begin{scope}
        \clip (0, 0) -- (0, 6mm) -- (120mm, 10mm) -- (120mm,0) ;
        \node (CN) at (60mm, 2mm) [anchor=base, text height=40mm, text depth=4mm, fill=lightcolor, inner sep=0] {%
          \Large\color{darkcolor}\strut~~~\putconfname~~~~\strut%
        } ;
      \end{scope}
      \fi
  \end{tikzpicture}%
  \clearpage%
}

\def\makethanks#1{%
  \noindent\begin{tikzpicture}
    % background & clipping
    \clip (0,0) rectangle (120mm, 90mm) ;
    \slidebackground{white}{95}{darkcolor}
    \begin{scope}
      \clip (0,44mm) -- (0, 90mm) -- (120mm, 90mm) -- (120mm, 48mm);
      \fill [darkcolor] (0,0) rectangle (120mm, 90mm) ;
      \slidebackground{darkcolor}{80}{white}
    \end{scope}
    % text
    \node (TT) at (60mm, 46mm) [anchor=south, text width=\paperwidth, text centered] {%
      \color{lightcolor}\huge\strut\putmaintitle%
          \ifmainsubtitlepresent\\ \Large \putmainsubtitle\fi%
    } ;
    \node at (TT.south) [anchor=north, yshift=-1mm] {%
      \begin{minipage}{104mm}%
        \centering\Huge\strut%
        #1
      \end{minipage}%
    } ;
    % footer
    \ifconfnamepresent
      \ifmaintitlepresent
      \begin{scope}
        \clip (0, 0) -- (0, 6mm) -- (120mm, 10mm) -- (120mm,0) ;
        \node (CN) at (60mm, 2mm) [anchor=base, text height=40mm, text depth=4mm, fill=lightcolor, inner sep=0] {%
          \Large\color{darkcolor}\strut~~~\putconfname~~~~\strut%
        } ;
      \end{scope}
      \fi
  \end{tikzpicture}%
  \clearpage%
}


\long\def\hilight#1{{\color{darkcolor}#1}}
\def\hilightbox#1{%
  \begin{tikzpicture}[baseline=(N.base)]
    \node (N) [rounded corners=1mm, fill=darkcolor, inner sep=0.4mm, text height=1.5ex, text depth=0.5ex] {\color{white}#1} ;
  \end{tikzpicture}%
}

\def\paramverb#1#2{%
  \global\edef\paramverbaccu{}%
  \def\paramverbaux##1{%
    \ifthenelse{\equal{##1}{#2}}{%
      \def\paramverbaux{%
        #1{\paramverbaccu}%
        \catcode`\^=7\catcode`\$=3\catcode`\#=6%
        \catcode`\~=10\catcode`\ =10\catcode`\_=8\catcode`\{=1%
        \catcode`\}=2\catcode`\$=3\catcode`\&=4\catcode`\#=6%
      }%
    }{%
      \global\edef\paramverbaccu{\paramverbaccu##1}%
    }%
    \paramverbaux%
  }
  \catcode`\^=12\catcode`\$=12\catcode`\#=12%
  \catcode`\~=12\catcode`\ =12\catcode`\_=12\catcode`\{=12%
  \catcode`\}=12\catcode`\$=12\catcode`\&=12\catcode`\#=12%
  \paramverbaux%
}

\def\hilightboxverb#1{\def\hilighttt##1{\hilightbox{\tt##1}}\paramverb{\hilighttt}{#1}}
\def\hilightverb#1{\def\hilighttt##1{\hilight{\tt##1}\xspace}\paramverb{\hilighttt}{#1}}

\renewcommand{\picture}[2][0.5\linewidth]{
  \par \medskip {\centering
    \begin{tikzpicture}
      \node [inner sep=0] (H) {\includegraphics[width=#1]{#2}} ;
    \end{tikzpicture}
 \par} \medskip
}

\newcommand{\ocplogo}{%
  {\fontspec[Scale=MatchLowercase]{Linux Biolinum O}\selectfont%
    OCaml\kern0.5ex\begin{tikzpicture}[baseline=(X.base)]
    \node (X) [rounded corners=0.5ex, fill, inner sep=0.5ex, text depth={}, text height={}] {\color{white}PRO} ;
  \end{tikzpicture}}\xspace%
}

\newcommand{\tezoslogo}[1][white]{%
  {\begin{tikzpicture}[baseline=(X.base)]
   \node (X) [fill, inner sep=0.2ex, text depth={}, text height={}, shape=circle, text width=] {\color{#1}\tez} ;
  \end{tikzpicture}}\xspace%
}

\newcommand{\ocpshortlogo}{%
  {\begin{tikzpicture}[baseline=(X.base)]
    \node (X) [rounded corners=0.5ex, fill, inner sep=0.5ex, text depth={}, text height={}] {\color{white}OCP} ;
  \end{tikzpicture}}\xspace%
}

\def\tableofcontents{
  \begin{slide}
    \title{Outline}
    \centering
    \begin{tikzpicture}
      \node (TT) [fill=lightcolor, text width=0.7\linewidth, text centered] {\large\strut\completetoc} ;
    \end{tikzpicture}
  \end{slide}
}
\def\pro{{\Large\fontspec[Scale=MatchLowercase]{DejaVu Sans}\selectfont\hilight{⊕}}}
\def\con{{\Large\fontspec[Scale=MatchLowercase]{DejaVu Sans}\selectfont\hilight{⊖}}}
\def\same{{\Large\fontspec[Scale=MatchLowercase]{DejaVu Sans}\selectfont\hilight{⊜}}}
